# .streamlit/secrets.toml

[snowflake]
user = "SVC_SPRING_DATASCIENCE"
password = "silla!_lepidoptera682"
account = "KYA28640"
warehouse = "ANALYSTS_WH"
database = "CD_ANALYTICS_TESTDB"
schema = "OMKAR"
